replicaCount: 1

image:
  repository: bellamy/wallos
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: true
  annotations: {}
  name: ''

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8888

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: wallos.kayabox.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wallos-tls
      hosts:
        - wallos.kayabox.local

persistence:
  db:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    mountPath: '/var/www/html/db'

  logos:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 500Mi
    mountPath: '/var/www/html/images/uploads/logos'

environment:
  TZ: 'America/Sao_Paulo'

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
