apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallos
  namespace: wallos
spec:
  project: default
  source:
    repoURL: https://kayaman.github.io/wallos
    targetRevision: HEAD
    path: wallos
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wallos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
